spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/platform_db
    username: springuser
    password: q1w2e3r4
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate.default_schema: public
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: "h4G8vB9xL2dQ7yNkX3pZ6tPmW9JH2S3O48zA5B7fLKC="
  expiration: 3600000